backend:
  # Change tag to camera to enable image recognition
  image: quay.io/rhdevelopers/roshambo-backend:buttons
  bot: true
  ainamespace: rps-ai-service

  # Do not change. Backend is not designed to scale horizontally.
  replicas: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2"

frontend:
  image: quay.io/rhdevelopers/roshambo-frontend:latest
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"
